# Generated by Django 4.0.4 on 2022-05-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options_alter_account_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
