# Generated by Django 4.0.4 on 2022-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answers_number_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='assessments',
            field=models.IntegerField(blank=True, verbose_name='Avaliações'),
        ),
    ]
