# Generated by Django 4.0.4 on 2022-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_answers_number_assessments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='number_assessments',
            field=models.IntegerField(default=1, verbose_name='Quantidade de avaliações'),
            preserve_default=False,
        ),
    ]
