# Generated by Django 4.0.4 on 2022-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_answers_answer_user_alter_answers_assessments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_user',
            field=models.CharField(default=1, max_length=10000, verbose_name='Resposta'),
            preserve_default=False,
        ),
    ]
