# Generated by Django 4.0.4 on 2022-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_answers_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='assessments',
            field=models.IntegerField(blank=True, default=0, verbose_name='Avaliações'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Curtidas'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='number_assessments',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número de avaliações'),
        ),
    ]
