# Generated by Django 4.0.4 on 2022-05-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_answers_assessments_alter_answers_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='assessments_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='likes_voted',
            field=models.BooleanField(default=False),
        ),
    ]
