# Generated by Django 4.0.4 on 2022-05-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0018_answers_assessments_voted_answers_likes_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='assessments_voted',
            field=models.BooleanField(default=False, verbose_name='Usuário atual votou?'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='likes_voted',
            field=models.BooleanField(default=False, verbose_name='Usuário atual curtiu?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
