# Generated by Django 4.0.4 on 2022-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_answers_assessments_voted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='answers',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment_user', to='questions.comments', verbose_name='Comentários'),
        ),
    ]
