# Generated by Django 4.0.4 on 2022-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_rename_comments_comments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='comments',
        ),
        migrations.AddField(
            model_name='answers',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_users', to='questions.comments', verbose_name='Comentários'),
        ),
    ]
