# Generated by Django 4.0.4 on 2022-05-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_remove_answers_comments_answers_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='comment',
            new_name='comments',
        ),
    ]
