# Generated by Django 4.0.4 on 2022-05-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_rename_comment_answers_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_user',
            new_name='response',
        ),
    ]
