# Generated by Django 4.0.4 on 2022-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_rename_answer_user_answers_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.CharField(choices=[('T', 'Todos os niveis'), ('EF', 'Ensino fundamental (básico)'), ('EM', 'Ensino médio (secundário)'), ('ES', 'Ensino superior')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
