# Generated by Django 4.0.4 on 2022-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_questions_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.CharField(choices=[('EF', 'Ensino fundamental (básico)'), ('EM', 'Ensino médio (secundário)'), ('ES', 'Ensino superior')], max_length=2),
        ),
    ]
