# Generated by Django 4.0.4 on 2022-05-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_alter_questions_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data de criação'),
        ),
    ]
