# Generated by Django 4.0.4 on 2022-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_alter_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(),
        ),
    ]
