# Generated by Django 4.0.4 on 2022-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_alter_questions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Todas', 'Todas'), ('Enem', 'Enem'), ('Matemática', 'Matemática'), ('História', 'História'), ('Geografia', 'Geografia'), ('Biologia', 'Biologia'), ('Português', 'Português'), ('Física', 'Física'), ('Química', 'Química'), ('Sociologia', 'Sociologia'), ('Administração', 'Administração'), ('Pedagogia', 'Pedagogia'), ('Inglês', 'Inglês'), ('Artes', 'Artes'), ('Saúde', 'Saúde'), ('Ed. Física', 'Ed. Física'), ('Contabilidade', 'Contabilidade'), ('Direito', 'Direito'), ('Pisicologia', 'Pisicologia'), ('Informática', 'Informática'), ('Lógica', 'Lógica'), ('Ed. Moral', 'Ed. Moral'), ('Espanhol', 'ArEspanholes'), ('Música', 'Música'), ('Ed. Técnica', 'Ed. Técnica')], max_length=50, verbose_name='Categoria'),
        ),
    ]
