# Generated by Django 4.0.6 on 2022-07-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_alter_questions_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
